### ISSUE TITLE
Setup UI not displayed

### ISSUE THREAD

**Issue by bsoener** [QuickSander/homebridge-mieleathome#10]
I can't access my homebridge since the update. When I removed this plugin my Homebridge was working again. 
<img width="918" alt="Bildschirmfoto 2021-01-27 um 19 44 43" src="https://user-images.githubusercontent.com/77502899/106038406-35fe6900-60d8-11eb-894d-ae986ec2e855.png">

<img width="1149" alt="Bildschirmfoto 2021-01-27 um 19 35 02" src="https://user-images.githubusercontent.com/77502899/106038425-3c8ce080-60d8-11eb-963e-514e3f4da98d.png">

under json config this plugin is not displayed. Use Firefox.

**Comment by QuickSander** [comment]
Thanks, I will push a new update of the plugin now which contains the removal of starting the setup server.

There is a slight chance this is the cause, so worth trying as setup code is in development phase anyway.

**Comment by QuickSander** [comment]
Could you try the latest version v2.1.1 ?

**Comment by bsoener** [comment]
yes. Have now performed an update. Can not configure the Miele plugin. In the Json config it is also not listed.

**Comment by QuickSander** [comment]
I'm really puzzled. Since I do not know how to possibly break it on my side, it is very hard to find the cause. 
What OS do you run? 
Is the logging still the same?

**Comment by bsoener** [comment]
My Macbook version is the 11.1
As soon as i paste the config.json the configuration my homebridge crashes. what i don't understand before the update came out everything went smoothly. also no new plugin was installed or anything changed.

**Comment by QuickSander** [comment]
What exactly do you put in the config? Please note the "breaking changes". Platform name _must_ be "Miele@home".

**Comment by bsoener** [comment]
{
            "name": "Miele@Home",
            "token": "xxxxxxxxxxxxxxxxxxx",
            "pollInterval": 60,
            "platform": "Miele@Home"
        },

**Comment by QuickSander** [comment]
Your platform name must be "Miele@home" (lower case 'h')

Could you reverify you have the latest v2.1.1 installed?

**Comment by bsoener** [comment]
yes. Is the latest version. H-h changed and it works now. Great!!! thanks for your help.

**Comment by QuickSander** [comment]
but still the UI does not display? Or does it? Since then I might have a hunch what is wrong.
