### ISSUE TITLE
miele api issue

### ISSUE THREAD

**Issue by bolvz** [QuickSander/homebridge-mieleathome#13]
when I login to miele api website
api.mcs3.miele.com, 
some error below
{"code":500,"message":"A technical error occured. Please try again later. (Error-ID: fbb92fe63265043f)"}

**Comment by QuickSander** [comment]
Could you explain exactly how you get to the website?
As of the later versions, you would not need to manually browse to the website to login. The plugin should guide you to that website.

- Did you browse there manually or did you use the setup form the plugin?
- If you browsed manually to the website. Why?

If you did use th plugins setup and that's what you mean with "I login to", then I guess it is a temporary outage of the Miele server unfortunately and you have to try again later. Are you sure your clientID and clientSecret are correct?

**Comment by bolvz** [comment]
When I use plugin with correct Id and secret, it turned into such error page.
Is it a temporary server error? If so, when it can be fixed?

Thanks,

Regards,
Zhangmeng

**Comment by QuickSander** [comment]
_If so, when it can be fixed?_
I have no idea. You would have to ask Miele. The plugin redirects you to their website to login with them. 

I do not encounter this error. 
Did you try logging in using the Miele app itself?
If that also doesn't work, it is positively on 
Miele's side.

**Comment by bolvz** [comment]
I can login with Miele app, but cannot go to next step using plugin which redirect to the error page.

Regards,
Zhangmeng

**Comment by bolvz** [comment]
Btw, I am also asking Miele, till now no feedback:(

Regards,
Zhangmeng

**Comment by QuickSander** [comment]
See my previous question. Which region are you logging in from?

Can you try the following link? If this doesn't work I really cannot help and it is on Miele's side. The. I would suggest to be patient until Miele fixes it. Again, I just tried and all went successfully for me. 

https://api.mcs3.miele.com/thirdparty/login?client_id=your client id&response_type=code&redirect_uri=http://localhost&state=1

**Comment by bolvz** [comment]
I have tried your  link with my client id, and then showed Miele's account, password and country request.
I entered my miele account, password and China as country, but error again{"code":500,"message":"A technical error occured. Please try again later. (Error-ID: c6659c265db13f05)"}

**Comment by bolvz** [comment]
I am logging from China.
I have tried your link with my client id, and then showed a page with link https://api.mcs3.miele.com/thirdparty/login?client_id=6a8156f8-9265-450f-be72-462be1120f16&response_type=code&redirect_url=http://localhost&state=1
<img width="693" alt="image" src="https://user-images.githubusercontent.com/11473604/108356771-83797c00-7227-11eb-93c1-3371be58b122.png">

**Comment by bolvz** [comment]
I am logging from China.
I have tried your link with my client id, and then showed a page with link https://api.mcs3.miele.com/thirdparty/login?client_id=6a8156f8-9265-450f-be72-462be1120f16&response_type=code&redirect_uri=http://localhost&state=1
<img width="868" alt="image" src="https://user-images.githubusercontent.com/11473604/108362807-25e92d80-722f-11eb-9733-b35c6376163d.png">

when I  entered my account id and password chose country China 
<img width="794" alt="image" src="https://user-images.githubusercontent.com/11473604/108362934-516c1800-722f-11eb-9ac3-027f3d0067a5.png">

It displayed as follows,
<img width="928" alt="image" src="https://user-images.githubusercontent.com/11473604/108363081-7bbdd580-722f-11eb-85b5-8315581bd412.png">

if I chose other country like UK, it displayed following page
<img width="802" alt="image" src="https://user-images.githubusercontent.com/11473604/108363265-b162be80-722f-11eb-8fd9-acd76d960b9e.png">

**Comment by QuickSander** [comment]
Oké, thanks now it is clear. I'm sorry to say this is entirely on the Miele server side. The plugin's code is not involved in this case nor touched or .

Did you make your Miele@home credentials with the same region you select here?

The fact that the UK version fails is sort of understandable as your Miele account region should match with the selection you make in the login screen I think.

**Comment by bolvz** [comment]
yes, I wrote mail to miele for serval times, now the miele said they are working fix it.....

**Comment by bolvz** [comment]
yes. I am asking miele to fix this issue, but they are still working on it.
--
