### ISSUE TITLE
Error: Accessories must be created with a non-empty displayName.

### ISSUE THREAD

**Issue by SkyCZ** [QuickSander/homebridge-mieleathome#16]
Hi, im getting this error after setting up the plugin and restarting homebridge.
Any idea why it has an empty displayName?

`[2/19/2021, 6:52:03 PM] [Miele@home] Discovered device: id: 153657114, name: , model: RX2
[2/19/2021, 6:52:03 PM] [Miele@home] Error: Accessories must be created with a non-empty displayName.
    at new Accessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:232:29)
    at new PlatformAccessory (/usr/lib/node_modules/homebridge/src/platformAccessory.ts:69:9)
    at MieleAtHomePlatform.discoverDevices (/usr/lib/node_modules/homebridge-mieleathome/src/platform.ts:139:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`

**Comment by QuickSander** [comment]
Oké, seems I need to make it robust against a possibly empty name.
Could you dump swagger output from [Miele Swagger](https://www.miele.com/developer/swagger-ui/swagger.html#/Information/get_devices) for the /devices request?
I want to verify Miele really returns no name for your appliance.

**Comment by QuickSander** [comment]
Could you try v2.5.1 just now published?

**Comment by SkyCZ** [comment]
`{
  "153657114": {
    "ident": {
      "type": {
        "key_localized": "Device type",
        "value_raw": 23,
        "value_localized": ""
      },
      "deviceName": "",
      "deviceIdentLabel": {
        "fabNumber": "153657114",
        "fabIndex": "00",
        "techType": "RX2",
        "matNumber": "10673800",
        "swids": [
          "108",
          "111",
          "102",
          "1"
        ]
      },
      "xkmIdentLabel": {
        "techType": "",
        "releaseVersion": ""
      }
    },
    "state": {
      "ProgramID": {
        "value_raw": 3,
        "value_localized": "Turbo",
        "key_localized": "Program name"
      },
      "status": {
        "value_raw": 255,
        "value_localized": "Not connected",
        "key_localized": "status"
      },
      "programType": {
        "value_raw": 0,
        "value_localized": "Programa",
        "key_localized": "Program type"
      },
      "programPhase": {
        "value_raw": 0,
        "value_localized": "",
        "key_localized": "Program phase"
      },
      "remainingTime": [
        0,
        0
      ],
      "startTime": [
        0,
        0
      ],
      "targetTemperature": [],
      "temperature": [],
      "signalInfo": false,
      "signalFailure": false,
      "signalDoor": false,
      "remoteEnable": {
        "fullRemoteControl": true,
        "smartGrid": false,
        "mobileStart": false
      },
      "ambientLight": null,
      "light": null,
      "elapsedTime": [
        0,
        0
      ],
      "spinningSpeed": {
        "unit": "rpm",
        "value_raw": null,
        "value_localized": null,
        "key_localized": "Spin speed"
      },
      "dryingStep": {
        "value_raw": null,
        "value_localized": "",
        "key_localized": "Drying level"
      },
      "ventilationStep": {
        "value_raw": null,
        "value_localized": "",
        "key_localized": "Fan level"
      },
      "plateStep": [],
      "ecoFeedback": null,
      "batteryLevel": 85
    }
  },
  "000101817629": {
    "ident": {
      "type": {
        "key_localized": "Device type",
        "value_raw": 7,
        "value_localized": "Dishwasher"
      },
      "deviceName": "",
      "deviceIdentLabel": {
        "fabNumber": "000101817629",
        "fabIndex": "60",
        "techType": "G5930",
        "matNumber": "07728070",
        "swids": [
          "61705",
          "61449"
        ]
      },
      "xkmIdentLabel": {
        "techType": "XKM3000Z",
        "releaseVersion": "01.02"
      }
    },
    "state": {
      "ProgramID": {
        "value_raw": 2264924160,
        "value_localized": "",
        "key_localized": "Program name"
      },
      "status": {
        "value_raw": 1,
        "value_localized": "Off",
        "key_localized": "status"
      },
      "programType": {
        "value_raw": 0,
        "value_localized": "Programa",
        "key_localized": "Program type"
      },
      "programPhase": {
        "value_raw": 1792,
        "value_localized": "",
        "key_localized": "Program phase"
      },
      "remainingTime": [
        0,
        0
      ],
      "startTime": [
        0,
        0
      ],
      "targetTemperature": [],
      "temperature": [],
      "signalInfo": false,
      "signalFailure": false,
      "signalDoor": true,
      "remoteEnable": {
        "fullRemoteControl": true,
        "smartGrid": true,
        "mobileStart": false
      },
      "ambientLight": null,
      "light": null,
      "elapsedTime": [
        0,
        0
      ],
      "spinningSpeed": {
        "unit": "rpm",
        "value_raw": null,
        "value_localized": null,
        "key_localized": "Spin speed"
      },
      "dryingStep": {
        "value_raw": null,
        "value_localized": "",
        "key_localized": "Drying level"
      },
      "ventilationStep": {
        "value_raw": null,
        "value_localized": "",
        "key_localized": "Fan level"
      },
      "plateStep": [],
      "ecoFeedback": null,
      "batteryLevel": null
    }
  },
  "mac-001D63FFFE0204B5": {
    "ident": {
      "type": {
        "key_localized": "Device type",
        "value_raw": 12,
        "value_localized": "Oven"
      },
      "deviceName": "",
      "deviceIdentLabel": {
        "fabNumber": "",
        "fabIndex": "",
        "techType": "",
        "matNumber": "",
        "swids": [
          "35591",
          "0"
        ]
      },
      "xkmIdentLabel": {
        "techType": "XKM3000Z",
        "releaseVersion": "01.16"
      }
    },
    "state": {
      "ProgramID": {
        "value_raw": 2348810240,
        "value_localized": "",
        "key_localized": "Program name"
      },
      "status": {
        "value_raw": 2,
        "value_localized": "On",
        "key_localized": "status"
      },
      "programType": {
        "value_raw": 1,
        "value_localized": "Own programme",
        "key_localized": "Program type"
      },
      "programPhase": {
        "value_raw": 3072,
        "value_localized": "Cooling phase",
        "key_localized": "Program phase"
      },
      "remainingTime": [
        0,
        0
      ],
      "startTime": [
        64,
        0
      ],
      "targetTemperature": [
        {
          "value_raw": -32768,
          "value_localized": null,
          "unit": "Celsius"
        },
        {
          "value_raw": -32768,
          "value_localized": null,
          "unit": "Celsius"
        }
      ],
      "temperature": [
        {
          "value_raw": 2400,
          "value_localized": 24,
          "unit": "Celsius"
        },
        {
          "value_raw": -32768,
          "value_localized": null,
          "unit": "Celsius"
        }
      ],
      "signalInfo": false,
      "signalFailure": false,
      "signalDoor": false,
      "remoteEnable": {
        "fullRemoteControl": false,
        "smartGrid": false,
        "mobileStart": false
      },
      "ambientLight": null,
      "light": null,
      "elapsedTime": [
        0,
        0
      ],
      "spinningSpeed": {
        "unit": "rpm",
        "value_raw": null,
        "value_localized": null,
        "key_localized": "Spin speed"
      },
      "dryingStep": {
        "value_raw": null,
        "value_localized": "",
        "key_localized": "Drying level"
      },
      "ventilationStep": {
        "value_raw": null,
        "value_localized": "",
        "key_localized": "Fan level"
      },
      "plateStep": [],
      "ecoFeedback": null,
      "batteryLevel": null
    }
  },
  "000111097297": {
    "ident": {
      "type": {
        "key_localized": "Device type",
        "value_raw": 27,
        "value_localized": "Hob"
      },
      "deviceName": "",
      "deviceIdentLabel": {
        "fabNumber": "000111097297",
        "fabIndex": "56",
        "techType": "KM6314 R01",
        "matNumber": "07510810",
        "swids": [
          "2331",
          "0"
        ]
      },
      "xkmIdentLabel": {
        "techType": "XKS 3000 Z",
        "releaseVersion": "V1.30"
      }
    },
    "state": {
      "ProgramID": {
        "value_raw": 2600468480,
        "value_localized": "",
        "key_localized": "Program name"
      },
      "status": {
        "value_raw": 1,
        "value_localized": "Off",
        "key_localized": "status"
      },
      "programType": {
        "value_raw": 0,
        "value_localized": "Programa",
        "key_localized": "Program type"
      },
      "programPhase": {
        "value_raw": 0,
        "value_localized": "",
        "key_localized": "Program phase"
      },
      "remainingTime": [
        0,
        0
      ],
      "startTime": [
        0,
        0
      ],
      "targetTemperature": [],
      "temperature": [],
      "signalInfo": false,
      "signalFailure": false,
      "signalDoor": false,
      "remoteEnable": {
        "fullRemoteControl": false,
        "smartGrid": false,
        "mobileStart": false
      },
      "ambientLight": null,
      "light": null,
      "elapsedTime": [],
      "spinningSpeed": {
        "unit": "rpm",
        "value_raw": null,
        "value_localized": null,
        "key_localized": "Spin speed"
      },
      "dryingStep": {
        "value_raw": null,
        "value_localized": "",
        "key_localized": "Drying level"
      },
      "ventilationStep": {
        "value_raw": null,
        "value_localized": "",
        "key_localized": "Fan level"
      },
      "plateStep": [
        {
          "value_raw": 0,
          "value_localized": "0",
          "key_localized": "Power level"
        },
        {
          "value_raw": 0,
          "value_localized": "0",
          "key_localized": "Power level"
        },
        {
          "value_raw": 0,
          "value_localized": "0",
          "key_localized": "Power level"
        },
        {
          "value_raw": 0,
          "value_localized": "0",
          "key_localized": "Power level"
        }
      ],
      "ecoFeedback": null,
      "batteryLevel": null
    }
  },
  "000703279237": {
    "ident": {
      "type": {
        "key_localized": "Device type",
        "value_raw": 17,
        "value_localized": "Coffee machine"
      },
      "deviceName": "",
      "deviceIdentLabel": {
        "fabNumber": "000703279237",
        "fabIndex": "10",
        "techType": "CVA7845",
        "matNumber": "11107640",
        "swids": [
          "5005",
          "25211",
          "25210",
          "4860",
          "25245",
          "5141",
          "5366",
          "25133",
          "20442",
          "25246",
          "5056",
          "20441",
          "25209",
          "5214",
          "20366",
          "20462"
        ]
      },
      "xkmIdentLabel": {
        "techType": "EK037",
        "releaseVersion": "03.82"
      }
    },
    "state": {
      "ProgramID": {
        "value_raw": 0,
        "value_localized": "",
        "key_localized": "Program name"
      },
      "status": {
        "value_raw": 1,
        "value_localized": "Off",
        "key_localized": "status"
      },
      "programType": {
        "value_raw": 0,
        "value_localized": "Programa",
        "key_localized": "Program type"
      },
      "programPhase": {
        "value_raw": 4352,
        "value_localized": "",
        "key_localized": "Program phase"
      },
      "remainingTime": [
        0,
        0
      ],
      "startTime": [
        0,
        0
      ],
      "targetTemperature": [
        {
          "value_raw": -32768,
          "value_localized": null,
          "unit": "Celsius"
        },
        {
          "value_raw": -32768,
          "value_localized": null,
          "unit": "Celsius"
        },
        {
          "value_raw": -32768,
          "value_localized": null,
          "unit": "Celsius"
        }
      ],
      "temperature": [
        {
          "value_raw": -32768,
          "value_localized": null,
          "unit": "Celsius"
        },
        {
          "value_raw": -32768,
          "value_localized": null,
          "unit": "Celsius"
        },
        {
          "value_raw": -32768,
          "value_localized": null,
          "unit": "Celsius"
        }
      ],
      "signalInfo": false,
      "signalFailure": false,
      "signalDoor": false,
      "remoteEnable": {
        "fullRemoteControl": true,
        "smartGrid": false,
        "mobileStart": false
      },
      "ambientLight": null,
      "light": 2,
      "elapsedTime": [],
      "spinningSpeed": {
        "unit": "rpm",
        "value_raw": null,
        "value_localized": null,
        "key_localized": "Spin speed"
      },
      "dryingStep": {
        "value_raw": null,
        "value_localized": "",
        "key_localized": "Drying level"
      },
      "ventilationStep": {
        "value_raw": null,
        "value_localized": "",
        "key_localized": "Fan level"
      },
      "plateStep": [],
      "ecoFeedback": null,
      "batteryLevel": null
    }
  }
}`

Sorry for the late response, version v2.5.2 seems to have fixed it.

Here is the console log after updating.
`2/24/2021, 3:40:22 PM] [Miele@home] Discovered device: id: 153657114, name: Unnamed 153657114, model: RX2
[2/24/2021, 3:40:22 PM] [Miele@home] Ignoring unsupported device. Device: "Unnamed 153657114" with raw type value: 23.
[2/24/2021, 3:40:22 PM] [Miele@home] Discovered device: id: 000101817629, name: Dishwasher, model: G5930
[2/24/2021, 3:40:22 PM] [Miele@home] ... adding temperature sensor.
[2/24/2021, 3:40:22 PM] [Miele@home] Registering new accessory: Dishwasher
[2/24/2021, 3:40:22 PM] [Miele@home] Discovered device: id: mac-001D63FFFE0204B5, name: Oven, model: Unknown Miele model
[2/24/2021, 3:40:22 PM] [Miele@home] Ignoring unsupported device. Device: "Oven" with raw type value: 12.
[2/24/2021, 3:40:22 PM] [Miele@home] Discovered device: id: 000111097297, name: Hob, model: KM6314 R01
[2/24/2021, 3:40:22 PM] [Miele@home] Ignoring unsupported device. Device: "Hob" with raw type value: 27.
[2/24/2021, 3:40:22 PM] [Miele@home] Discovered device: id: 000703279237, name: Coffee machine, model: CVA7845
[2/24/2021, 3:40:22 PM] [Miele@home] Ignoring unsupported device. Device: "Coffee machine" with raw type value: 17.`

**Comment by SkyCZ** [comment]
Also any plans to support other devices in the future?

**Comment by QuickSander** [comment]
Thanks, so it indeed seems Miele leaves device names empty nevertheless fills model name. I changed the code to do the best effort to compile a proper device name. If all fails it will add "Unknown Miele <serial number>" now.

> Also any plans to support other devices in the future?
Yes, see [Planned Features](https://github.com/QuickSander/homebridge-mieleathome#planned-features). I have fridge support in the making.

I hope you agree to close the issue now.
