### ISSUE TITLE
WCG370 compatibility request

### ISSUE THREAD

**Issue by luckfamousa** [QuickSander/homebridge-mieleathome#2]
After installing the plugin and setup I see this in homebridge logs.

[11/01/2021, 21:24:48] [Miele@Home] Discovered device: id: xxx, name: Washing machine, model: WCG370
[11/01/2021, 21:24:48] [Miele@Home] Skipping unsupported device "Washing machine with type identifier: 1.

(Slightly censored) Response from `curl -X GET "https://api.mcs3.miele.com/v1/devices?language=en" -H "accept: application/json; charset=utf-8" -H "Authorization: Bearer xxx"`

```json
{
  "xxx": {
    "ident": {
      "type": {
        "key_localized": "Device type",
        "value_raw": 1,
        "value_localized": "Washing machine"
      },
      "deviceName": "",
      "deviceIdentLabel": {
        "fabNumber": "xxx",
        "fabIndex": "19",
        "techType": "WCG370",
        "matNumber": "11283770",
        "swids": [
          "5031",
          "20456",
          "25213",
          "25191",
          "25304",
          "25205",
          "25312",
          "25319",
          "5031",
          "20456",
          "25213",
          "25191",
          "25304",
          "25205",
          "25312",
          "25319"
        ]
      },
      "xkmIdentLabel": {
        "techType": "EK037",
        "releaseVersion": "03.58"
      }
    },
    "state": {
      "ProgramID": {
        "value_raw": 3,
        "value_localized": "Minimum iron",
        "key_localized": "Program name"
      },
      "status": {
        "value_raw": 5,
        "value_localized": "In use",
        "key_localized": "status"
      },
      "programType": {
        "value_raw": 1,
        "value_localized": "Own programme",
        "key_localized": "Program type"
      },
      "programPhase": {
        "value_raw": 260,
        "value_localized": "Main wash",
        "key_localized": "Program phase"
      },
      "remainingTime": [
        1,
        33
      ],
      "startTime": [
        0,
        0
      ],
      "targetTemperature": [
        {
          "value_raw": 3000,
          "value_localized": 30,
          "unit": "Celsius"
        },
        {
          "value_raw": -32768,
          "value_localized": null,
          "unit": "Celsius"
        },
        {
          "value_raw": -32768,
          "value_localized": null,
          "unit": "Celsius"
        }
      ],
      "temperature": [
        {
          "value_raw": -32768,
          "value_localized": null,
          "unit": "Celsius"
        },
        {
          "value_raw": -32768,
          "value_localized": null,
          "unit": "Celsius"
        },
        {
          "value_raw": -32768,
          "value_localized": null,
          "unit": "Celsius"
        }
      ],
      "signalInfo": false,
      "signalFailure": false,
      "signalDoor": false,
      "remoteEnable": {
        "fullRemoteControl": true,
        "smartGrid": false,
        "mobileStart": false
      },
      "light": 0,
      "elapsedTime": [
        0,
        5
      ],
      "spinningSpeed": {
        "unit": "rpm",
        "value_raw": 1200,
        "value_localized": "1200",
        "key_localized": "Spin speed"
      },
      "dryingStep": {
        "value_raw": null,
        "value_localized": "",
        "key_localized": "Drying level"
      },
      "ventilationStep": {
        "value_raw": null,
        "value_localized": "",
        "key_localized": "Fan level"
      },
      "plateStep": [],
      "ecoFeedback": {
        "currentWaterConsumption": {
          "unit": "l",
          "value": 12
        },
        "currentEnergyConsumption": {
          "unit": "kWh",
          "value": 0.1
        },
        "waterForecast": 0.4,
        "energyForecast": 0.3
      },
      "batteryLevel": null
    }
  }
}
```

**Comment by QuickSander** [comment]
Thanks a lot . Will attempt to release a new version tonight (CET+1).

**Comment by QuickSander** [comment]
Clear. Please do understand the HomeKit limitations that the maximum amount for remaining duration is 1h. So only the last hour you will see an accurate "Remaining Time" countdown. I'm not yet aware of any way to solve this differently. Maybe a sensor of some kind.

**Comment by luckfamousa** [comment]
I mean from a practical perspective 60 min should be ok for most usage scenarios.
On the other hand modeling it as a sensor would probably work as well.

**Comment by QuickSander** [comment]
According to the Miele API documentation your washing machine should also support powerOn and powerOff actions. Could you dump the swagger output for actions when the machine is standby and in use? I think it is not allowed when the system is running a washing program.  Strange that these actions are not supported for my washer dryer, but it is for a washer.

**Comment by luckfamousa** [comment]
Machine is in standby right now. `https://api.mcs3.miele.com/v1/devices/xxx/actions` gives me

```json
{
  "processAction": [],
  "light": [],
  "ambientLight": [],
  "startTime": [],
  "ventilationStep": [],
  "programId": [],
  "targetTemperature": [],
  "deviceName": false,
  "powerOn": true,
  "powerOff": false,
  "colors": [],
  "modes": []
}
```

Example value:

```json
{
  "processAction": [
    1,
    2
  ],
  "light": [],
  "startTime": [
    [
      0,
      0
    ],
    [
      23,
      59
    ]
  ],
  "ventilationStep": [],
  "programId": [],
  "targetTemperature": [],
  "deviceName": true,
  "powerOn": false,
  "powerOff": true,
  "colors": [],
  "modes": []
}
```

It also says
> In the current state the 'processAction', 'startTime', 'deviceName' and 'powerOff' action is available for the Washing machine

I try to call the API tomorrow when the machine is running.

**Comment by luckfamousa** [comment]
State in Standby

```json
{
  "ProgramID": {
    "value_raw": 3,
    "value_localized": "Minimum iron",
    "key_localized": "Program name"
  },
  "status": {
    "value_raw": 1,
    "value_localized": "Off",
    "key_localized": "status"
  },
  "programType": {
    "value_raw": 1,
    "value_localized": "Own programme",
    "key_localized": "Program type"
  },
  "programPhase": {
    "value_raw": 268,
    "value_localized": "Finished",
    "key_localized": "Program phase"
  },
  "remainingTime": [
    0,
    0
  ],
  "startTime": [
    0,
    0
  ],
  "targetTemperature": [
    {
      "value_raw": 3000,
      "value_localized": 30,
      "unit": "Celsius"
    },
    {
      "value_raw": -32768,
      "value_localized": null,
      "unit": "Celsius"
    },
    {
      "value_raw": -32768,
      "value_localized": null,
      "unit": "Celsius"
    }
  ],
  "temperature": [
    {
      "value_raw": -32768,
      "value_localized": null,
      "unit": "Celsius"
    },
    {
      "value_raw": -32768,
      "value_localized": null,
      "unit": "Celsius"
    },
    {
      "value_raw": -32768,
      "value_localized": null,
      "unit": "Celsius"
    }
  ],
  "signalInfo": false,
  "signalFailure": false,
  "signalDoor": false,
  "remoteEnable": {
    "fullRemoteControl": true,
    "smartGrid": false,
    "mobileStart": false
  },
  "light": 0,
  "elapsedTime": [
    0,
    0
  ],
  "spinningSpeed": {
    "unit": "rpm",
    "value_raw": 1200,
    "value_localized": "1200",
    "key_localized": "Spin speed"
  },
  "dryingStep": {
    "value_raw": null,
    "value_localized": "",
    "key_localized": "Drying level"
  },
  "ventilationStep": {
    "value_raw": null,
    "value_localized": "",
    "key_localized": "Fan level"
  },
  "plateStep": [],
  "ecoFeedback": null,
  "batteryLevel": null
}
```

**Comment by QuickSander** [comment]
Could you try v1.1.0? It should at least recognise your washing machine. It should also allow you to stop the washing machine when your device allows it according to its run state.

**Comment by luckfamousa** [comment]
Yes!

[15/01/2021, 21:02:16] [Miele@Home] Discovered device: id: xxx, name: Washing machine, model: WCG370
[15/01/2021, 21:02:16] [Miele@Home] Registering new accessory: Washing machine

**Comment by QuickSander** [comment]
I see I need to request devices with a certain locale name. `?language=de` based on configuration setting. Dann sollten Sie "Waschmaschine" sehen.

**Comment by luckfamousa** [comment]
I today tested it while the machine was running. In Homebridge I can see the timer. Which looks like this:
![image](https://user-images.githubusercontent.com/243384/104843181-851eef80-58c9-11eb-80ad-2b9a33a79bbc.png)

However in HomeKit I just see a button that says running without any time information on it. When long pressing that button I get a view that also shows the countdown. But when just normally pressing that button it interrupts the machine which then resulted in this:
![image](https://user-images.githubusercontent.com/243384/104843311-3d4c9800-58ca-11eb-8d13-ce9279a57fbd.png)

Is it somehow possible to limit the functionality on countdown (and if possible alarm, when the machine has finished)? I don't see a real use case for stopping it from remote (even if accidents like the one today don't happen).

**Comment by QuickSander** [comment]
HomeKit doesn't know the concept of Washing machines so I had to mimic it as a water tap. That being said, I also do not have control over how the Apple Home app displays remaining time etc. It is indeed in:
- Apple Home app: Long press to see it (but limited to 3600s).
- Eve app: You see it always (but also limited to 3600s by the HomeKit API).

Only when the Miele API allows to stop the machine, it will issue a stop command or start command when you short press on it. I made it so just to get as much as possible already standard Miele functionality into HomeKit. Sorry to see Miele somewhere made a mistake that results in your washing machine not properly handling stop, but the Miele app itself will yield the same result I imagine. I could make an option where you disable the short press action via the config.json options.

The alarm when finished: This is why I started making this plugin as with this plugin it now allows you to make any automation you want using HomeKit. E.g. sound the HomePod or turn on a light when the washing machine finishes. The water tap Homekit control does not by itself set an alarm. You have to go into automations to add one to your liking. I would recommend using the Eve app for that which is much more elaborate and exposes more HomeKit options than the Apple Home app itself.

**Comment by MichelRabozee** [comment]
By the way, I have a question about automation: when I try in the Home app to create an automation to be notified (by the HomePod for instance) that the Washing Machine program completes for instance, I cannot select the Valve accessory representing the appliance (it does not appear in the list of accessories being controlled. Do I need to do something special for that ?

**Comment by QuickSander** [comment]
Yes, that is the way. Unfortunately Apple's Home app is still targeted pretty much only for simple users. Eve supports more HomeKit options, but doesn't yet support shortcuts or playing music. So mostly I use a combination of both.
