### ISSUE TITLE
Warning: characteristic was supplied illegal value: number 1 exceeded minimum of 10

### ISSUE THREAD

**Issue by grzegorz914** [QuickSander/homebridge-mieleathome#20]
After update to 2.7.0

`[7.03.2021, 08:42:16] [homebridge-mieleathome] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 1 exceeded minimum of 10. See https://git.io/JtMGR for more info.`

**Comment by QuickSander** [comment]
Acknowledged. Being discussed in the discussion forum also. I'm afraid there is no simple solution. HomeKit's minimum target temp is 10°C while we desire a range between 0 and 10°C for fridges. I'm pushing the boundaries of what HomeKit allows.

**Comment by grzegorz914** [comment]
just adapt min and max value:

https://github.com/homebridge/HAP-NodeJS/blob/410f40032c21dc4bf9ffd63e00e04c7ddd3f79f2/src/lib/definitions/CharacteristicDefinitions.ts#L4143

**Comment by QuickSander** [comment]
The thing is that is exactly what I'm doing already since the first experimental version of Fridge support. So scratch the "just" 😉

**Comment by QuickSander** [comment]
The new version at least reduces the amount of warnings by preventing to update the characteristic each and every poll interval.

**Comment by grzegorz914** [comment]
Are U Try this part of code do set correct Mina and max value for Target Temperature :

```
accessory.getService(Service.Thermostat)
  .getCharacteristic(Characteristic.TargetTemperature)
  .setProps({
    minValue: 0,
    maxValue: 30,
    minStep: 1
  });
```

**Comment by QuickSander** [comment]
Thanks, but: yes, that is exactly the code I already had built-in since the first version. (Except with 1-9 step 1). Otherwise the target temperature dial would not show the scale 1-9 step 1 if I did not have done that.

**Comment by QuickSander** [comment]
Is this issue still present for you with v2.7.2?

**Comment by grzegorz914** [comment]
No,

The warning is gone

**Comment by QuickSander** [comment]
Later version returned the problem, but I have finally found the root cause. See #23.
