### ISSUE TITLE
Unable to set target temp, off instead of temperature

### ISSUE THREAD

**Issue by QuickSander** [QuickSander/homebridge-mieleathome#22]
![2 7 2](https://user-images.githubusercontent.com/291583/110683377-39f3cf80-81dc-11eb-881b-8a40b440cc40.jpg)
I hope you will not kill me :-)

2.7.2 fixes the temperature for the dish washer and wash machine, and still no Warning or Error at startup !

but I think two side effects occur:

(1) there is now an "Off" label where the target temperature for fridge used to be. And this "Off" label remains even if you change the target temperature.

And BTW, when you do change the target temperature, a 400 error now appears in the log:
```
[10/03/2021 19:45:07] [Miele] Miele API request https://api.mcs3.miele.com/v1/devices/mac-00124B0005AB4D8B/actions failed. Status 400: "Bad Request".Error: Request failed with status code 400
```

(2) whilst my washing machine is switched off, it now appears "Running" (Active = 1, In Use = 0)
I am quite sure it was not the case with 2.7.1 (a switched off wash machine was Active = 0, In Use = 0). Strangely enough, I went back installing 2.7.1, 2.7.0, even 2.6.1 but I could no more get the Fridge to display the Target Temperature or the Wash Machine to indicate "Off" when it is off (I guess it is due to caching, but I always fear the consequences of deleting caches...)

_Originally posted by @MichelRabozee in https://github.com/QuickSander/homebridge-mieleathome/discussions/15#discussioncomment-464797_

**Comment by QuickSander** [comment]
Oké this is not good. Especially since somehow the behaviours you mention are totally unrelated to my latest changes (on first  sight).

I hope you will not kill _me_ because of this flakey quality. Honestly unintentional though. I did test it (sort of).

**Comment by QuickSander** [comment]
Can you enable Homebridge debug logging and paste what  the first few poll actions parsed from the MieleAPI from the log?
Since I cannot reproduce the behaviour of (2) and (1) sounds like a side-effect of (2). If inUse = 0 target temp cannot be set.

You can by the way via the GUI just remove the cache for specific accessories

**Comment by MichelRabozee** [comment]
Again, sorry to have given you bad news, moreover, wrong bad news. I will check my local systems more carefully in the future before writing something ;-)
