### ISSUE TITLE
Disabling temperature sensor for Dish Washer does not work

### ISSUE THREAD

**Issue by MichelRabozee** [QuickSander/homebridge-mieleathome#25]
Hello,

I played a bit today with some settings I never touched :-)

I disabled the "temperature sensor" for my dish washer, and it still appears (the log also still says "Lave-vaisselle: Adding temperature sensor.")

I did the same for the Washing Machine, and it worked: the log said "removing temperature sensor" and it was effective.

**Comment by QuickSander** [comment]
A typo in the enum name.
