### ISSUE TITLE
1.2.0 "Active = 0" while running ("In Use = 1") and also when standby ("In Use = 0" but Switched ON)

### ISSUE THREAD

**Issue by MichelRabozee** [QuickSander/homebridge-mieleathome#4]
Hello,

I think I discovered a small regression:

I just installed 1.2.0 over 1.1.1 and noticed that when an appliance like "Dish Washer" is running, the Active status is set to 0 while In Use is correctly "1". This leads to the appliance being displayed as going towards the STOP state (the Icon in Home app shows a spinning icon with "Arrêt..." as displayed status text - sorry, app in French, maybe "Stopping..." in English -) regardless of the fact it is running. Also, a switched on appliance in stand-by is now seen as "Switched Off" (active and in use = 0)

In version 1.1.1, both "active" and "in use" were set to "1" when the appliance was running, hence the Icon in Home app correctly displayed a pouring tap with the remaining time while the appliance is running. Also, when the Washing Machine was switched ON (Stand By), the "active" was "1" and "in use" was "0".

PS thanks for the "Thanks" ;-)

**Comment by MichelRabozee** [comment]
I think I found some issues in the new logic about active/inactive states.
In mieleCharacteristics.ts, function "update":
```javascript
  update(response: MieleStatusResponse): void {
    
    if(this.inactiveStates===null && this.activeStates===null) {
      throw new Error('Only supply valid inactive or active states, not both.');
    }

    if(this.inactiveStates && this.inactiveStates.includes(response.status.value_raw)) {
      this.state = this.offState;
    } else {
      this.state = this.onState;
    }

    if(this.activeStates && this.activeStates.includes(response.status.value_raw)) {
      this.state = this.onState;
    } else {
      this.state = this.offState;
    }
    
    this.platform.log.debug(`Parsed ${this.characteristicType.name} from API response: ${this.state}`);
    this.service.updateCharacteristic(this.characteristicType, this.state); 
  }
```
In case the activeStates array is null (as in our case), this.state is eventually always set to this.offState.

Also, I do not undestand this.inactiveStates===null && this.activeStates===null   giving error "Only supply valid inactive or active states, not both".
Shouldn't the test be "this.inactiveStates !== null && this.activeStates !== null" ?

Maybe (if you agree with my remarks of course), the code could be changed to:
```javascript
  update(response: MieleStatusResponse): void {
    
    if (this.inactiveStates !== null && this.activeStates !== null) {
      throw new Error('Only supply valid inactive or active states, not both.');
    }

    if (this.inactiveStates) {
      if (this.inactiveStates.includes(response.status.value_raw)) {
          this.state = this.offState;
      } else {
          this.state = this.onState;
      }
    }

    if (this.activeStates) {
      this.activeStates.includes(response.status.value_raw)) {
        this.state = this.onState;
      } else {
        this.state = this.offState;
      }
    }
    
    this.platform.log.debug(`Parsed ${this.characteristicType.name} from API response: ${this.state}`);
    this.service.updateCharacteristic(this.characteristicType, this.state); 
  }
```

**Comment by QuickSander** [comment]
Hi, sorry I missed this issue. I will take a look. I recognise the problem. I'm currently building auto refresh token functionality (before I hit my 30 days token limit ;-), will take this along.

**Comment by QuickSander** [comment]
> (the Icon in Home app shows a spinning icon with "Arrêt..." as displayed status text - sorry, app in French, maybe "Stopping..." in English -) 

The new plugin version actually has a language selection to get the French / Walonie word for "Dish washer", but unfortunately the Miele API currently only support English and German. (no Dutch or French...)
