### ISSUE TITLE
Error Message: Client credentials are not valid

### ISSUE THREAD

**Issue by Chimpepe** [QuickSander/homebridge-mieleathome#55]
Hi Guys,

I'm trying to Manually retrieve token as shown in Wiki but on Step 4. I get the "Client credentials are not valid" Message.

Any Ideas how to fix this?

**Comment by bsoener** [comment]
exactly the same

**Comment by Chimpepe** [comment]
Sorry, my fault. I have now created a new dev account at miele and reconfigured the plugin. Everything works now! Thanks!
