### ISSUE TITLE
Power on coffee machine

### ISSUE THREAD

**Issue by dennisbekker** [QuickSander/homebridge-mieleathome#62]
Hi, if i turn on the coffee machine with the homebridge app and the device clean itself, it does that after some time powered off, its nothing more than flushing some water, the coffee machine gives 3 beeping errors and flashing led lights. power on and off after that wont causing the issue again. so the cleaning process generates a error when powering on. if i use the button on the coffee machine to power on, no errors or beeping, also turning on with the miele home app no beeping or flashing leds. i have a video of the issue if you want. power off is working perfectly if i turn the coffee machine on manual with the button or the miele home app.

**Comment by dennisbekker** [comment]
Update, it happens also when using the Miele app so it has nothing to do with this app on homebridge. i get the same error beeps when powering on the miele coffee machine with the miele app.

**Comment by QuickSander** [comment]
Oké, thanks. If you don't mind I will close this issue now.
