### ISSUE TITLE
State: Starting

### ISSUE THREAD

**Issue by Maddin1684** [QuickSander/homebridge-mieleathome#68]
Hello,

since a few days the state of my MIELE washing machine is set to „starting“. 
But it is turned off…

many ideas or workarounds?

**Comment by Maddin1684** [comment]
Since today same problem with my dryer. The characteristic is set to 1.

what can I do?

**Comment by QuickSander** [comment]
Can you post the Homebridge logging of the Miele@Home plugin?

**Comment by Maddin1684** [comment]
Hi! Problem solved!
I‘ve lost the connection with the Miele App. 
After a reconnect everything worked fine

**Comment by QuickSander** [comment]
Thanks. Somehow awkward the Miele app influences the results obtained by the Homebridge plugin though.
