### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by StefanGebhardt** [QuickSander/homebridge-mieleathome#73]
Hi, I have a Miele@Home-Account. But where can I find the Client-ID? And what's the client secret? Is it the password?
Unfortunately no hint in documentation.
And the link to Miele@home in the documentation is not totally correct: you first have to select a country, otherwise you don't find a possibility to get an account.
And wants about the "Authorization grant server port."? Also no hint in the documentation...

**Comment by drheck** [comment]
Hi Stefan,
go to this website (it is the second link for gettimg a devolper account) https://www.miele.com/developer/.
Click on get involved and fill the two fields and register the app.
The name of your application is not really important.
Then you should get the needed credentials for the plugin.
I hope this helped.
Peter

**Comment by StefanGebhardt** [comment]
Worked, thank you!
