### ISSUE TITLE
Zero installation instructions, plugin doesn't work

### ISSUE THREAD

**Issue by Fatalution** [QuickSander/homebridge-mieleathome#82]
I installed it. It asks for my Client ID and Client Secret. 
Where do I get them? What is the client authorization port? Where is the wiki? Where are any kind of instructions for the plugin?

**Comment by keepers1221** [comment]
You are able to get these by signing up to the api using the below link.  You need to take note of them as they aren't displayed again once you click the link in the email.

https://www.miele.com/f/com/en/register_api.aspx

https://forums.homeseer.com/forum/hs4-products/hs4-plugins/lighting-primary-technology-plug-ins-aa/miele-stefxx/1476416-client-id-and-client-secret

**Comment by QuickSander** [comment]
> I installed it. It asks for my Client ID and Client Secret. Where do I get them? What is the client authorization port? Where is the wiki? Where are any kind of instructions for the plugin?

Cool. Homepage contains exactly what you are demanding since the dawn of this project.
