### ISSUE TITLE
Introduce stopping state mapped on finished and cancelled.

### ISSUE THREAD

**Issue by QuickSander** [QuickSander/homebridge-mieleathome#9]
Currently the mapping is as follows:

Miele State | HomeKit InUse | HomeKit Active | Displayed in Home
------------|----------------|----------------|-------------------
  Off = 1       | 0                         | 0                        | Off
  ProgramSelected = 3 | 0      | 1                         | Starting
  WaitingToStart = 4 | 0          | 1                         | Starting
  InUse = 5 | 1                          | 1                         | Running
  Finished = 7 | 0                     | 1                         | Starting
  Cancelled = 9 | 0                  | 1                         | Starting 

Finished / Cancelled could be mapped as follows instead:

Miele State | HomeKit InUse | HomeKit Active | Displayed in Home
------------|----------------|----------------|-------------------
  Off = 1       | 0                         | 0                        | Off
  ProgramSelected = 3 | 0      | 1                         | Starting
  WaitingToStart = 4 | 0          | 1                         | Starting
  InUse = 5 | 1                          | 1                         | Running
  Finished = 7 | 1                     | 0                         | Stopping
  Cancelled = 9 | 1                  | 0                         | Stopping 

@MichelRabozee Would this be an improvement, or would it break your automation possibilities?

_Originally posted by @QuickSander in https://github.com/QuickSander/homebridge-mieleathome/discussions/8_

**Comment by MichelRabozee** [comment]
Hi, as I wrote earlier in the #8, no problem with automation (in Eve, you can act both on inUse and active), hence having it like the new mapping should be an improvement.

**Comment by MichelRabozee** [comment]
Just a feedback: this logic works perfectly !!!
